name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
      - name: Spotless + Detekt
        run: |
          ./gradlew spotlessCheck detekt
      - name: Test
        run: |
          ./gradlew test
      - name: Build fat jar
        run: |
          ./gradlew :server:shadowJar
      # Optional: Build Docker image (no push)
      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: oneread/server:ci
